apiVersion: v1
kind: Pod
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: '11601'
    prometheus.io/scrape: 'true'
  labels:
    component: kube-cert-validity-check
    tier: control-plane
  name: kube-cert-validity-check
  namespace: kube-system
spec:
  containers:
  - name: kube-cert-validity-check
    image: registry.cn-shanghai.aliyuncs.com/zywdockers/images:kube-cert-validity-check-0.0.4
    imagePullPolicy: IfNotPresent
    ports:
    - name: metrics
      containerPort: 11601
    volumeMounts:
    - mountPath: /etc/kubernetes/pki
      name: k8s-certs
      readOnly: true
  hostNetwork: true
  priorityClassName: system-cluster-critical
  volumes:
  - hostPath:
      path: /etc/kubernetes/pki
      type: DirectoryOrCreate
    name: k8s-certs
